import type { QuestionCle } from "./structure";

// Les 116 questions posées au candidat (ADR-0019), dans l'ordre de présentation de
// l'IPIP-NEO-300 (numéro croissant : les sous-dimensions alternent).
//
// Sources :
//   - sélection, sous-dimensions et sens : Johnson (2014), IPIP-NEO-120,
//     https://ipip.ori.org/30FacetNEO-PI-RItems.htm (domaine public) ;
//   - texte français : Thiry, B., & Piolti, M. (2023, 12 février). IPIP NEO 300, adaptation
//     française européenne, tableau 5, fondée sur la traduction québécoise de M. Gravel.
//     https://benjaminthiry.netlify.app/posts/2023-02-12-ipipneo300fr/
//
// Seules retouches : apostrophe typographique et point final. Les 4 questions de O6
// (opinions politiques : n° 28, 58, 148, 268) ne sont jamais posées.
// Adaptation française NON validée : ne jamais qualifier ce questionnaire de « validé ».

export interface Question extends QuestionCle {
  texte: string;
}

export const QUESTIONS: readonly Question[] = [
  { numero: 1, facette: "N1", inversee: false, texte: "Je m’inquiète à propos de choses." },
  { numero: 2, facette: "E1", inversee: false, texte: "Je me fais des amis facilement." },
  { numero: 3, facette: "O1", inversee: false, texte: "J’ai une imagination débordante." },
  { numero: 4, facette: "A1", inversee: false, texte: "Je fais confiance aux autres." },
  { numero: 5, facette: "C1", inversee: false, texte: "Je complète les tâches avec succès." },
  { numero: 6, facette: "N2", inversee: false, texte: "Je me mets en colère facilement." },
  { numero: 7, facette: "E2", inversee: false, texte: "J’adore les grandes fêtes." },
  { numero: 8, facette: "O2", inversee: false, texte: "Je crois en l’importance de l’art." },
  { numero: 11, facette: "N3", inversee: false, texte: "Je me sens souvent triste." },
  { numero: 12, facette: "E3", inversee: false, texte: "Je prends les choses en main." },
  { numero: 13, facette: "O3", inversee: false, texte: "Je vis mes émotions intensément." },
  { numero: 17, facette: "E4", inversee: false, texte: "Je suis toujours occupé." },
  { numero: 18, facette: "O4", inversee: false, texte: "Je préfère la variété à la routine." },
  { numero: 22, facette: "E5", inversee: false, texte: "J’adore les sensations fortes." },
  { numero: 26, facette: "N6", inversee: false, texte: "Je panique facilement." },
  { numero: 27, facette: "E6", inversee: false, texte: "Je respire la joie." },
  { numero: 29, facette: "A6", inversee: false, texte: "Je sympathise avec les sans-abri." },
  { numero: 31, facette: "N1", inversee: false, texte: "Je crains le pire." },
  { numero: 33, facette: "O1", inversee: false, texte: "J’aime me perdre dans mes idées." },
  {
    numero: 34,
    facette: "A1",
    inversee: false,
    texte: "Je crois que les autres ont de bonnes intentions.",
  },
  { numero: 35, facette: "C1", inversee: false, texte: "J’excelle dans ce que je fais." },
  { numero: 36, facette: "N2", inversee: false, texte: "Je suis facilement irrité." },
  {
    numero: 37,
    facette: "E2",
    inversee: false,
    texte: "Je parle à plusieurs personnes en soirée.",
  },
  { numero: 40, facette: "C2", inversee: false, texte: "J’aime faire du rangement." },
  { numero: 41, facette: "N3", inversee: false, texte: "Je ne m’aime pas." },
  { numero: 42, facette: "E3", inversee: false, texte: "J’essaie de diriger les autres." },
  { numero: 43, facette: "O3", inversee: false, texte: "Je ressens les émotions des autres." },
  { numero: 45, facette: "C3", inversee: false, texte: "Je tiens mes promesses." },
  { numero: 47, facette: "E4", inversee: false, texte: "Je suis toujours en mouvement." },
  { numero: 50, facette: "C4", inversee: false, texte: "Je travaille dur." },
  { numero: 52, facette: "E5", inversee: false, texte: "Je recherche l’aventure." },
  { numero: 53, facette: "O5", inversee: false, texte: "J’adore lire des documents stimulants." },
  { numero: 55, facette: "C5", inversee: false, texte: "Je suis toujours préparé." },
  { numero: 56, facette: "N6", inversee: false, texte: "Je me sens dépassé par les événements." },
  { numero: 57, facette: "E6", inversee: false, texte: "Je m’amuse beaucoup." },
  {
    numero: 59,
    facette: "A6",
    inversee: false,
    texte: "J’ai de la sympathie pour les gens plus démunis que moi.",
  },
  { numero: 61, facette: "N1", inversee: false, texte: "J’ai peur de plusieurs choses." },
  { numero: 62, facette: "E1", inversee: false, texte: "Je me sens confortable avec les gens." },
  { numero: 63, facette: "O1", inversee: false, texte: "J’adore rêvasser." },
  {
    numero: 64,
    facette: "A1",
    inversee: false,
    texte: "J’ai confiance en ce que les gens disent.",
  },
  { numero: 65, facette: "C1", inversee: false, texte: "Je gère les tâches facilement." },
  {
    numero: 68,
    facette: "O2",
    inversee: false,
    texte: "Je vois une beauté dans les choses que d’autres pourraient ne pas remarquer.",
  },
  { numero: 71, facette: "N3", inversee: false, texte: "Il m’arrive souvent de broyer du noir." },
  { numero: 74, facette: "A3", inversee: false, texte: "J’adore aider les autres." },
  {
    numero: 76,
    facette: "N4",
    inversee: false,
    texte: "J’éprouve de la difficulté à aborder les autres.",
  },
  {
    numero: 77,
    facette: "E4",
    inversee: false,
    texte: "Je fais beaucoup de choses dans mes temps libres.",
  },
  {
    numero: 86,
    facette: "N6",
    inversee: false,
    texte: "Je me sens incapable de gérer les choses.",
  },
  { numero: 91, facette: "N1", inversee: false, texte: "Je deviens stressé facilement." },
  { numero: 93, facette: "O1", inversee: false, texte: "J’aime me perdre dans mes pensées." },
  {
    numero: 99,
    facette: "A2",
    inversee: true,
    texte: "J’utilise les autres pour mes propres fins.",
  },
  { numero: 104, facette: "A3", inversee: false, texte: "Je me préoccupe des autres." },
  { numero: 105, facette: "C3", inversee: false, texte: "Je dis la vérité." },
  {
    numero: 106,
    facette: "N4",
    inversee: false,
    texte: "J’ai peur d’attirer l’attention vers moi.",
  },
  { numero: 111, facette: "N5", inversee: false, texte: "Je fais des excès." },
  {
    numero: 120,
    facette: "C6",
    inversee: true,
    texte: "Je me lance dans les choses sans réfléchir.",
  },
  { numero: 126, facette: "N2", inversee: false, texte: "Je perds patience." },
  { numero: 132, facette: "E3", inversee: false, texte: "Je prends le contrôle des choses." },
  {
    numero: 136,
    facette: "N4",
    inversee: false,
    texte: "Je me sens seulement à l’aise avec mes amis.",
  },
  {
    numero: 138,
    facette: "O4",
    inversee: true,
    texte: "Je préfère m’en tenir aux choses connues.",
  },
  {
    numero: 140,
    facette: "C4",
    inversee: false,
    texte: "Je fais plus que ce que l’on attend de moi.",
  },
  { numero: 142, facette: "E5", inversee: false, texte: "J’agis de manière effrénée." },
  { numero: 144, facette: "A5", inversee: true, texte: "Je crois être meilleur que les autres." },
  { numero: 145, facette: "C5", inversee: false, texte: "Je réalise mes objectifs." },
  { numero: 147, facette: "E6", inversee: false, texte: "J’adore la vie." },
  {
    numero: 149,
    facette: "A6",
    inversee: true,
    texte: "Je ne suis pas intéressé par les problèmes des autres.",
  },
  { numero: 150, facette: "C6", inversee: true, texte: "Je prends des décisions impulsives." },
  {
    numero: 155,
    facette: "C1",
    inversee: false,
    texte: "Je sais comment faire avancer les choses.",
  },
  { numero: 157, facette: "E2", inversee: true, texte: "Je préfère être seul." },
  { numero: 159, facette: "A2", inversee: true, texte: "Je triche pour avancer." },
  {
    numero: 160,
    facette: "C2",
    inversee: true,
    texte: "J’oublie souvent de remettre les choses à leur place.",
  },
  {
    numero: 162,
    facette: "E3",
    inversee: true,
    texte: "J’attends que les autres prennent les devants.",
  },
  { numero: 165, facette: "C3", inversee: true, texte: "J’enfreins les règles." },
  { numero: 167, facette: "E4", inversee: true, texte: "J’aime prendre ça mollo." },
  { numero: 168, facette: "O4", inversee: true, texte: "Je n’aime pas les changements." },
  { numero: 169, facette: "A4", inversee: true, texte: "J’adore une bonne bagarre." },
  { numero: 171, facette: "N5", inversee: true, texte: "Je fais rarement des excès." },
  { numero: 172, facette: "E5", inversee: false, texte: "J’agis de façon téméraire." },
  { numero: 174, facette: "A5", inversee: true, texte: "J’ai une haute estime de moi-même." },
  { numero: 176, facette: "N6", inversee: true, texte: "Je demeure calme sous pression." },
  { numero: 177, facette: "E6", inversee: false, texte: "Je regarde le bon côté de la vie." },
  { numero: 184, facette: "A1", inversee: true, texte: "Je ne fais pas confiance aux autres." },
  { numero: 188, facette: "O2", inversee: true, texte: "Je n’aime pas la poésie." },
  { numero: 190, facette: "C2", inversee: true, texte: "Je laisse ma chambre en désordre." },
  {
    numero: 194,
    facette: "A3",
    inversee: true,
    texte: "Je suis indifférent aux sentiments des autres.",
  },
  { numero: 195, facette: "C3", inversee: true, texte: "Je ne tiens pas mes promesses." },
  { numero: 199, facette: "A4", inversee: true, texte: "Je crie sur les gens." },
  { numero: 201, facette: "N5", inversee: true, texte: "Je résiste facilement à la tentation." },
  { numero: 203, facette: "O5", inversee: true, texte: "J’évite les discussions philosophiques." },
  { numero: 204, facette: "A5", inversee: true, texte: "J’ai une très bonne opinion de moi-même." },
  { numero: 205, facette: "C5", inversee: true, texte: "Je perds mon temps." },
  { numero: 210, facette: "C6", inversee: true, texte: "Je me précipite dans l’action." },
  { numero: 212, facette: "E1", inversee: true, texte: "J’évite le contact avec les autres." },
  { numero: 216, facette: "N2", inversee: true, texte: "Je ne suis pas facilement agacé." },
  {
    numero: 218,
    facette: "O2",
    inversee: true,
    texte: "Je n’apprécie pas aller à des musées d’art.",
  },
  { numero: 220, facette: "C2", inversee: true, texte: "Je laisse traîner mes choses." },
  {
    numero: 223,
    facette: "O3",
    inversee: true,
    texte: "Je remarque rarement mes réactions émotionnelles.",
  },
  { numero: 229, facette: "A4", inversee: true, texte: "J’insulte les gens." },
  { numero: 231, facette: "N5", inversee: true, texte: "Je suis capable de contrôler mes envies." },
  {
    numero: 233,
    facette: "O5",
    inversee: true,
    texte: "J’ai de la difficulté à comprendre les idées abstraites.",
  },
  {
    numero: 239,
    facette: "A6",
    inversee: true,
    texte: "Je tente de ne pas penser aux gens dans le besoin.",
  },
  { numero: 247, facette: "E2", inversee: true, texte: "J’évite les foules." },
  { numero: 249, facette: "A2", inversee: true, texte: "Je profite des autres." },
  { numero: 251, facette: "N3", inversee: true, texte: "Je suis à l’aise avec moi-même." },
  {
    numero: 256,
    facette: "N4",
    inversee: true,
    texte: "Je ne suis pas dérangé par les situations sociales difficiles.",
  },
  { numero: 259, facette: "A4", inversee: true, texte: "Je m’en prends aux autres." },
  {
    numero: 260,
    facette: "C4",
    inversee: true,
    texte: "Je fais juste assez de travail pour m’en sortir.",
  },
  {
    numero: 263,
    facette: "O5",
    inversee: true,
    texte: "Je ne suis pas intéressé par les discussions théoriques.",
  },
  { numero: 264, facette: "A5", inversee: true, texte: "Je me vante de mes vertus." },
  {
    numero: 265,
    facette: "C5",
    inversee: true,
    texte: "J’ai de la difficulté à commencer les tâches.",
  },
  { numero: 270, facette: "C6", inversee: true, texte: "J’agis sans réfléchir." },
  { numero: 272, facette: "E1", inversee: true, texte: "Je garde les autres à distance." },
  { numero: 279, facette: "A2", inversee: true, texte: "J’entrave les plans des autres." },
  { numero: 283, facette: "O3", inversee: true, texte: "Je ne comprends pas les gens émotifs." },
  {
    numero: 284,
    facette: "A3",
    inversee: true,
    texte: "Je ne prends pas de temps pour les autres.",
  },
  {
    numero: 288,
    facette: "O4",
    inversee: true,
    texte: "Je suis attaché aux méthodes conventionnelles.",
  },
  {
    numero: 290,
    facette: "C4",
    inversee: true,
    texte: "Je mets peu de temps et d’efforts dans mon travail.",
  },
];

// Échelle de réponse, de 1 à 5, lue après « Cette phrase me décrit… » (maquette C3).
// Même sens que l'échelle de l'IPIP (de « très inexact » à « très exact ») en mots
// courts, qui tiennent en cinq cases sur un téléphone. Les contrôles d'attention
// (pages.ts) citent ces libellés : un test vérifie qu'ils existent.
export const ECHELLE_REPONSES = [
  { valeur: 1, libelle: "Pas du tout" },
  { valeur: 2, libelle: "Plutôt pas" },
  { valeur: 3, libelle: "Ni l’un ni l’autre" },
  { valeur: 4, libelle: "Plutôt" },
  { valeur: 5, libelle: "Tout à fait" },
] as const;
